language: node_js
cache:
  directories:
    - "~/.npm"
    - node_modules #Cache node_modules for faster builds
    - dist
notifications:
  email: false
node_js:
  - "stable"
install: true
jobs:
  include:
    - stage: install dependencies
      script: npm install
    - stage: test
      script: npm run test
    - stage: build
      script: npm run build
      skip_cleanup: true
    - stage: deploy to heroku staging
      if: branch = staging
      script: skip
      deploy: &heroku
        provider: heroku
        skip_cleanup: true # Don't re-run the tests
        api_key:
          secure: ijS/pjfcl3dLIkKQo/WRAxV7J4gnY74QZZ7DF270F2xGzdIob9AhaGdBrD8YXrKHqAtytBgWEtTL6C8XbIOg+12D9KY4jjD07Nhu6pNHW/d9KFaKnNA45UD5GTlpLsOKfquE95zmPGQq3+vI1ZDMMWf3mdGvJUO0INxW7ILjQsyzdyrSl4O0DUO+CCL1QghbkmIPklvvlymGzuotTwmPxvitEMji/Yqzus+LdyQjQmmtfvR4rLB5bvgIn/1hZPbbuLI7g532WsTEBS5O9OzubNn20pDmPhg8G69UBpBVVXPxUrrm2BN1BUGUy4ciXdXEEFdG5mkgMJiO8YvbGJkTdqSF82Ibp+NCCitBxN2er5Cy9Iq4hghjOdO4vzgfBAQrfo/5ZD8ah2DjE05uczQoVPrHu8ZyRV+UGmeOc4fI9J2hSZv7yqOe3OXEwvYG3wKSIbhjRH+pe7stbOlaSNgrp599Pf5dT2Lau3vbO/VsUYQ4OtH5PWG03Inhd2IUGShEmTRVsOYdVqg4a9/3FuVPaCfZJorUeELNYuugVuwjNaSJFAvvMqrYZxLarmResMINpknocH2mTQ8A/zBsQyGwpnf1E+26g6/RMh6Dmf7iieQv9wXuzz81w3ia+ZVp11UY+3R/IfVKolub2fP5B0EkKSJZiauraG29Vnzyh7BoJJI=
        app: js-accordion-staging
        on:
          repo: kappys1/js-accordion
          branch: staging
          condition: $TRAVIS_BRANCH = staging
    - stage: "deploy GH-PAGES to production"
      if: branch = master
      script: skip
      deploy: &pages
        provider: pages
        skip_cleanup: true
        verbose: true
        github_token: $GH_TOKEN # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: dist/doc
        on:
          branch: master
          condition: $TRAVIS_BRANCH = master
    - stage: npm release
      if: branch = master
      node_js: "stable"
      script: skip
      before_deploy:
        - npm run semantic-release
        - cp package.json dist/lib/package.json
        - cd dist/lib
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
branches:
  only:
    - master
    - staging
